version: '2'
services:
  db:
    container_name: postgre_sql
    image: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - '.env'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/rbac-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - '.env'
networks:
    default:
        external:
            name: rbacapi_default