version: '2'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/rbac-api
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    env_file:
      - '.env_rds'
networks:
    default:
        external:
            name: rbacapi_default